name: Build & Release

on:
  push:
    branches: [master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hypersynergism_release
          path: release/mod/hypersynergism_release.js

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: release/mod/hypersynergism_release.js
          generate_release_notes: true
